version: '3.2'
services:
    prometheus:
        image: prom/prometheus:latest
        volumes:
            - ./prometheus:/etc/prometheus/
        command:
            - --config.file=/etc/prometheus/prometheus.yml
        ports:
            - 9090:9090
        restart: always


    alertmanager-bot:
        command:
        - --alertmanager.url=http://alertmanager:9093
        - --log.level=info
        - --store=bolt
        - --bolt.path=/data/bot.db
        environment:       
          TELEGRAM_ADMIN: ${TL_ID}
          TELEGRAM_TOKEN: ${TL_TOKEN}
        image: metalmatze/alertmanager-bot:0.4.3
        ports:
        - 8080:8080
        restart: always
        volumes:
        - ./data:/data

    alertmanager:
      image: prom/alertmanager:v0.21.0
      user: "1000"
      ports:
        - 9093:9093
      volumes:
        - ./alertmanager/:/etc/alertmanager/
      restart: always
      command:
        - '--config.file=/etc/alertmanager/config.yml'
        - '--storage.path=/etc/alertmanager/data'
    

    node-exporter:
        image: prom/node-exporter
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        hostname: monitoring
        command:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --collector.filesystem.ignored-mount-points
            - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
        ports:
            - 9100:9100
        restart: always

    grafana:
        image: grafana/grafana:8.4.4
        depends_on:
            - prometheus
        user: "0"    
        ports:
            - 3000:3000
        volumes:
              - ./grafana:/var/lib/grafana
              - ./grafana/provisioning/:/etc/grafana/provisioning/
              
        restart: unless-stopped
    
    blackbox-exporter:
        image: prom/blackbox-exporter
        ports:
            - 9155:9155
        restart: always
        volumes:
            - ./blackbox:/config
        command: --config.file=/config/blackbox.yml


